### ISSUE TITLE
This work was published under the Apache License

### ISSUE THREAD

**Issue by frenck** [runDMCA/home-assistant-mazda#1]
Hi there 👋 

The license on this repo seems to be violating the license where large parts of this work is taken from.

Upstream license: <https://github.com/home-assistant/core/blob/7a060176b6ca779358c6b8f2b3ab4ef5d4e4b659/LICENSE.md>

Current license in this repo at the time of writing:

<https://github.com/runDMCA/home-assistant-mazda/blob/955206b30b53eb193eb1974eb99646de5940cbaa/LICENSE>

It also seems to embed `pymazda`, which (I think) wasn't published using the license provided with this repository.

**Comment by runDMCA** [comment]
@frenck, Thank you for the feedback. I have changed the license to match that of the original code. I will have to look further into pymazda and how it was originally licensed although it may not be possible since bdr99 removed the repository.
