### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by SethCalkins** [runDMCA/home-assistant-mazda#2]
Thanks for putting this back out there! Pulled my own custom integration and imported yours... all working great

**Comment by NessK** [comment]
Thank you so much Sir!

**Comment by Valdorama** [comment]
Absolute legend.

Resigned to the idea of losing Mazda integration forever and finally upgraded past 2023.10 yesterday. Then found this not even 24hrs later. Installed and everything is back up, totally seamless.

**Comment by cbrooker** [comment]
Just bought a Mazda today. Was really disappointed when I couldn't add to HA. Then I found this Repo. A huge Thank you from me.

**Comment by doosterkamp** [comment]
Awesome! Thanx!

**Comment by ilwalti** [comment]
Great job, mate!

**Comment by zghansar** [comment]
Is this still working? not working for me

**Comment by HansVanEijsden** [comment]
> Is this still working? not working for me

Still working here! 👍🏻

**Comment by ilwalti** [comment]
Yes it's working. Maybe your problem is the one that everyone has... you can connect only ONE user to My Mazda with privileges really useful, the other ones users you connect are useless. And you can have only ONE "admin" user connected at a time. So, if you use the My Mazda app on your phone (i.e.) you can't use this integration.
This is NOT AN INTEGRATION PROBLEM, i'ts just your usual friendly Mazda idiocracy...
My $0.02, of course.

**Comment by zghansar** [comment]
Ya worked, i was not doing it right

**Comment by guba91** [comment]
> Yes it's working. Maybe your problem is the one that everyone has... you can connect only ONE user to My Mazda with privileges really useful, the other ones users you connect are useless. And you can have only ONE "admin" user connected at a time. So, if you use the My Mazda app on your phone (i.e.) you can't use this integration. This is NOT AN INTEGRATION PROBLEM, i'ts just your usual friendly Mazda idiocracy... My $0.02, of course.

can you explain a bit more?
i've installed the mazda app on my android phone and with same credentials, logged in with the integration.
to improve functionality in home assistant i need to do what? just logoff and uninstall the app?

Thanks!!

**Comment by Valdorama** [comment]
I believe what you need to do is have a **separate** MyMazda user account for the HA integration, instead of using the same one you do with the MyMazda app.

In the MyMazda app, if you go to Settings > MyMazda > My Vehicle, there's a 'DRIVERS' tab where you can add additional drivers/accounts. I added a new one to use with the HA integration (with a different email address), and you can specify what permissions they have (you obviously need to give the new account some permissions so it can read the data).

**Comment by guba91** [comment]
> I believe what you need to do is have a **separate** MyMazda user account for the HA integration, instead of using the same one you do with the MyMazda app.
> 
> In the MyMazda app, if you go to Settings > MyMazda > My Vehicle, there's a 'DRIVERS' tab where you can add additional drivers/accounts. I added a new one to use with the HA integration (with a different email address), and you can specify what permissions they have (you obviously need to give the new account some permissions so it can read the data).

thanks you!! :D

**Comment by ilwalti** [comment]
> I believe what you need to do is have a **separate** MyMazda user account for the HA integration, instead of using the same one you do with the MyMazda app.
> 
> In the MyMazda app, if you go to Settings > MyMazda > My Vehicle, there's a 'DRIVERS' tab where you can add additional drivers/accounts. I added a new one to use with the HA integration (with a different email address), and you can specify what permissions they have (you obviously need to give the new account some permissions so it can read the data).

Yes, with _current_ version of the app this works fine. Previously, additional drivers didn't have enough permissions to see all data of the car. Thank you very much.

**Comment by GeorgeCastanza** [comment]
What does the integration show?  I took delivery of a new mazda today, and no data shows in the app (or HA?).  I'm wondering if it takes a while for the data to flow through to the app etc.  My 5 years free Roadside assistance is also showing as "expired" or something....so something it wrong.

**Comment by townsmcp** [comment]
> What does the integration show? I took delivery of a new mazda today, and no data shows in the app (or HA?). I'm wondering if it takes a while for the data to flow through to the app etc. My 5 years free Roadside assistance is also showing as "expired" or something....so something it wrong.

@GeorgeCastanza sounds like you need to enable Mazda Connected Services from the car dashboard itself so you can get updates in the Mazda app. As I recall, first time setup should also ask you for the car VIN
