### ISSUE TITLE
Multiple devices detected

### ISSUE THREAD

**Issue by crash0verride11** [runDMCA/home-assistant-mazda#3]
I don't know if this was an issue with the project before the DMCA, but I very promptly get logged out of the MyMazda app on other devices with the notification below. Pretty much all of the useful features are in HA now, but I do like using the Mazda app for my manual and such. Common problem? Any known way to mitigate? Reduce polling rate perhaps?

> **Multiple devices detected**
> Our records indicate that your MyMazda account is being accessed across multiple devices.

**Comment by jcbshw** [comment]
The original integration recommended creating a second "driver" to use with home assistant. In the settings go to "My Vehicle" to add one. I have one dedicated for home assistant.

**Comment by crash0verride11** [comment]
Bam, fixed. Thank you much.

@runDMCA Might be with noting in the ReadMe for anyone stumbling on this after the DMCA
